# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: "mjm.nethelpers/mjm.nethelpers/mjm.nethelpers.csproj"
  projectTest: "mjm.nethelpers/mjm.nethelpers.tests/mjm.nethelpers.tests.csproj"
  publishFolder: "mjm.nethelpers/bin/$(buildConfiguration)/netstandard2.0"
  
steps:
- task: NuGetToolInstaller@1

- task: GitVersion@5
  inputs:
    runtime: 'core'
    updateAssemblyInfo: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'



- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: "build"
    projects: "$(project)"
    arguments: "-c $(buildConfiguration)"


- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: "build"
    projects: "$(projectTest)"
    arguments: "-c $(buildConfiguration)"

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(projectTest)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '$(project)'
    versioningScheme: 'byBuildNumber'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'



